Add test for header error conditions
ethereumjs/ethereumjs-monorepo pull request #1234
Opened 2021-04-29 00:38 UTC by acolytec3

Partially addresses #1232 - Add 3 new tests for error conditions in `header.ts` that are currently not covered.

2021-04-29 00:39 UTC, acolytec3 commented
@holgerd77 As discussed in email, this is my first pass at a small to add coverage for part of `header.ts` that is currently missed in test coverage.

2021-04-29 11:15 UTC, holgerd77 requested changes
Hi @acolytec3,
nice, thanks a lot for this! 😄 

Some minor remarks, also linting fails on CI. Can you please run `npm run lint:fix`, and fix non-fixable things manually afterwards and commit and push? This is for having somewhat better code consistency and is always checked along a CI run.

2021-04-29 11:15 UTC, holgerd77 commented on packages/block/test/header.spec.ts
> +    testCase = 'show throw on invalid clique difficulty'
show -> should

2021-04-29 11:15 UTC, holgerd77 commented on packages/block/test/header.spec.ts
> +    st.throws(() => badHeader(), 'Invalid serialized header input. Must be array')
Some nit: "Invalid" -> "invalid" (all other test comments start with lowercase)

2021-04-29 11:15 UTC, holgerd77 commented on packages/block/test/header.spec.ts
> +      }
You can simplify with: `Array(16).fill(Buffer.alloc(0))`

2021-04-29 23:57 UTC, acolytec3 commented
@holgerd77 I've added functional tests for the `validateCliqueDifficulty` method in `header.ts` and I believe addressed all the linting issues.

2021-05-04 16:17 UTC, holgerd77 approved these changes
Thanks a lot, like this clean Mockchain setup 😄 , LGTM!

2021-05-04 16:17 UTC, merged

2021-05-04 16:20 UTC, holgerd77 commented
Ah, maybe some additional nit: since we are in a monorepo please label your both your PR title (e.g. "Block: Add...", have done this now directly) and your commits (e.g. `block: add test for header error conditions`) with the libraries touched, otherwise this is not giving enough context.