Common: removed retired dev networks
ethereumjs/ethereumjs-monorepo pull request #1296
Opened 2021-06-12 05:19 UTC by emersonmacro

2021-06-14 10:04 UTC, holgerd77 requested changes
Hi there,
thanks for the PR! 😄 

For the failing tx tests this is a bit laborious, but an upgrade is needed there. I also once stumbled upon this. This just needs a `Common` instance with the `london` HF activated, so this is not directly related to `aleut`. The thing is: once you change the network there some comparison values in the tests will also change, e.g. the hash in the `hash()` test case, since the hash function also takes the chain ID from the tx into account and the chain ID changes when the network changes.

So on these test cases you need to update - e.g. on the `hash()` test the expected hash to the new hash produced by `signed.hash()` (for now you can assume that this new hash is correct).

Also note: please use a stable/lasting network (like `mainnet` or `rinkeby` for replacement), if you use `calaveras` (the new dev network) e.g., the test will need some adoption again further down the line once *this* network is again removed. 😋

Ok, hope this helps, let me know if you have questions.

2021-06-15 04:22 UTC, emersonmacro commented on packages/common/src/genesisStates/index.ts
> -  baikal: require('./baikal.json'),
Ah, I missed that there were separate json files with the same names there. PR updated, files removed.

2021-06-15 04:24 UTC, emersonmacro commented
@holgerd77 Thank you - that info was very helpful. I converted the failing `tx` test to use `rinkeby` and tests are passing now

2021-06-15 08:33 UTC, holgerd77 approved these changes
Cool, thanks for working this in so quickly, looks really good now, will merge.

2021-06-15 08:33 UTC, merged