Monorepo: New Arrow Glacier Releases
ethereumjs/ethereumjs-monorepo pull request #1555
Opened 2021-11-05 12:35 UTC by holgerd77

2021-11-08 18:04 UTC, ryanio commented on packages/client/CHANGELOG.md
> +For the curageous there are instructions [here](https://hackmd.io/B1nMKhIiRBWRtgP4-d5KHw) on how to connect the EthereumJS client with a Lodestar Eth 2.0 client and produce blocks together. Note that
```suggestion
For the courageous there are instructions [here](https://hackmd.io/B1nMKhIiRBWRtgP4-d5KHw) on how to connect the EthereumJS client with a Lodestar Eth 2.0 client and produce blocks together. Note that specifications are changing quickly though and a new testnet is already planned, so this is not guaranteed to work.
```

2021-11-08 18:10 UTC, ryanio requested changes
LGTM! just a few comments

2021-11-08 18:10 UTC, ryanio commented on packages/client/CHANGELOG.md
> +The adventure "Mainnet sync" now comes to a halt though around the Shanghai dDoS attacks mainnet blocks ranging from 2,286,910 to 2,717,576 where we realize that our VM is just not optimized enough t
adventure?

2021-11-08 18:10 UTC, ryanio commented on packages/tx/CHANGELOG.md
> +Invalid Signature: s-values greater than secp256k1n/2 are considered invalid (tx type=1 hash=0xbf78bd19410294cb3c08fbbbdd675b4bd79e46b96b38e850091f5c03e0571be0 nonce=0 value=0 signed=true hf=london g
just a note, I found the `(size)` confusing after `accessList`, maybe later we can update it to `accessListCount=0`?

2021-11-08 18:11 UTC, ryanio commented on packages/client/CHANGELOG.md
> +The adventure "Mainnet sync" now comes to a halt though around the Shanghai dDoS attacks mainnet blocks ranging from 2,286,910 to 2,717,576 where we realize that our VM is just not optimized enough t
did you mean
> The "Mainnet sync" adventure now comes...

2021-11-08 18:16 UTC, ryanio commented on packages/client/CHANGELOG.md
> +The adventure "Mainnet sync" now comes to a halt though around the Shanghai dDoS attacks mainnet blocks ranging from 2,286,910 to 2,717,576 where we realize that our VM is just not optimized enough t
```suggestion
The "Mainnet sync" adventure now comes to a halt though around the Shanghai dDoS attacks mainnet blocks ranging from 2,286,910 to 2,717,576 where we realize that our VM is just not optimized enough to hold through these various edge case scenarios.
```

2021-11-08 18:18 UTC, ryanio submitted a review, later dismissed
lgtm!

2021-11-08 18:25 UTC, ryanio commented on packages/tx/CHANGELOG.md
> +Invalid Signature: s-values greater than secp256k1n/2 are considered invalid (tx type=1 hash=0xbf78bd19410294cb3c08fbbbdd675b4bd79e46b96b38e850091f5c03e0571be0 nonce=0 value=0 signed=true hf=london g
have updated in https://github.com/ethereumjs/ethereumjs-monorepo/pull/1555/commits/9304010d672a517f13ecb9048dab9176e6bfa09a

2021-11-08 18:26 UTC, ryanio approved these changes

2021-11-09 07:59 UTC, merged

2021-11-09 09:41 UTC, holgerd77 commented
Just published the following releases on npm:

- `@ethereumjs/common` [v2.6.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fcommon%402.6.0)
- `@ethereumjs/tx` [v3.4.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Ftx%403.4.0)
- `@ethereumjs/block` [v3.6.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fblock%403.6.0)
- `@ethereumjs/blockchain` [v5.5.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fblockchain%405.5.0)
- `@ethereumjs/vm` [v5.6.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fvm%405.6.0)
- `@ethereumjs/client` [v0.2.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fclient%400.2.0)