client: Add client protocol and synchronizer for snap sync
ethereumjs/ethereumjs-monorepo pull request #1897
Opened 2022-05-18 16:27 UTC by g11tech

This PR will enable fetching snap data for accounts,storage,codeby using the devp2p interface exposed in the PR: https://github.com/ethereumjs/ethereumjs-monorepo/pull/1883.  

Currently this PR is pointing to #1883, but when that gets merged, this PR will be updated to pointing master. This is so we can leverage the devp2p work being done in 1883 while independently developing some client capabilities with regard to consuming and fetching snap data (and get some early feedback)

### Curent status
`snap` protocol availability in the peer:
```typescript
[05-18|16:28:57] DEBUG Peer connected: id=e9631196 address=10.244.0.112:30303 transport=rlpx protocols=eth,snap inbound=false 
[05-18|16:28:57] DEBUG Found full peer: id=e9631196 address=10.244.0.112:30303 transport=rlpx protocols=eth,snap inbound=false 
[05-18|16:28:57] DEBUG Peer added: id=e9631196 address=10.244.0.112:30303 transport=rlpx protocols=eth,snap inbound=false 
```
Next Steps (all with a static peer):
- [x] Call getAccountRange on snap capable peer
- [x] Add remaining methods
 
Tests and coverage will follow via 
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/1933

2022-06-04 23:27 UTC, scorbajio commented
Started working on some tests in #1933.

2022-07-02 18:11 UTC, scorbajio commented
How has the "Call getAccountRange on snap capable peer" task been checked off when `getAccountRange` isn't implemented in a service? The best that we can do right now is mock the return value, right?

2022-07-02 18:40 UTC, g11tech commented
> @g11tech How has the "Call getAccountRange on snap capable peer" task been checked off when `getAccountRange` isn't implemented in a service? The best that we can do right now is mock the return value, right?

hey @scorbajio , yes you are right, but the checklist is with respect to calling & validating the method on another snap capable peer, hosting the methods i.e. providing the response via AccountRange replies is sort of not the scope of current PR. 

But yes, we can mock out the replies in test cases and fill them up!

2022-07-15 18:38 UTC, scorbajio commented
I'd like to begin working on the fetcher if no one has started yet. @jochem-brouwer @g11tech let me know if you are working on it so we don't duplicate work.

2022-07-15 19:03 UTC, g11tech commented
> I'd like to begin working on the fetcher if no one has started yet. @jochem-brouwer @g11tech let me know if you are working on it so we don't duplicate work.

awesome since i am a bit preoccupied by client related fixes, so it would be appreciated :heart: , 

let me do some rebasing on the current master for both snap-devp2p, snap-client (since the code has divereged quite abit) then may be you can take it forward, most probably by tomorrow. :slightly_smiling_face:

2022-07-17 17:45 UTC, g11tech commented
hey @scorbajio, you can work on the fetchers, and open it as a separate PR referencing this if you want,

in the meantime i can clean it up, and add some flags to that we can merge this in master as incremental approach is good.
What do you think @holgerd77

2022-07-24 14:57 UTC, holgerd77 commented
> What do you think @holgerd77

From my side that's ok. 👍

2022-08-04 14:04 UTC, g11tech commented
tests covering the client snap protocol will follow with this PR: https://github.com/ethereumjs/ethereumjs-monorepo/pull/1933

2022-08-04 18:13 UTC, acolytec3 requested changes
Looks pretty good though it's hard for me to judge on the functioning of the code at this point.  Will review the tests once that PR is ready for review and try to do some deeper testing on the protocol level to see that it works.

Left a few small comments I'd like addressed before we merge.

2022-08-04 18:13 UTC, acolytec3 commented on packages/client/lib/sync/snapsync.ts
> +    // Just a small snipped to test out the methods manually
```suggestion
    // Just a small snippet to test out the methods manually
```

2022-08-04 18:13 UTC, acolytec3 commented on packages/client/test/service/fullethereumservice.spec.ts
> +    t.ok(isTruthy(service.protocols.filter((p) => p instanceof EthProtocol)[0]), 'full protocol')
Could we check for length > 0 instead of using `isTruthy` here?

2022-08-04 18:13 UTC, acolytec3 commented on packages/client/test/service/fullethereumservice.spec.ts
> +      isTruthy(service.protocols.filter((p) => p instanceof LesProtocol)[0]),
Again, we shouldn't be using `isTruthy` here.  Check for length > 0

2022-08-04 18:13 UTC, acolytec3 commented on packages/client/test/service/fullethereumservice.spec.ts
> +    t.ok(isTruthy(service.protocols.filter((p) => p instanceof EthProtocol)[0]), 'full protocol')
Check for length greater than zero instead of using `isTruthy`

2022-08-04 18:27 UTC, acolytec3 commented
> #  **Performance Alert** 
> Possible performance regression was detected for benchmark. Benchmark result of this commit is worse than the previous benchmark result exceeding threshold `2`.
> 
> Benchmark suite	Current: [6318e87](https://github.com/ethereumjs/ethereumjs-monorepo/commit/6318e8786c84b72fc3878376f44d9bc2cfbd1d0d)	Previous: [623d8a0](https://github.com/ethereumjs/ethereumjs-monorepo/commit/623d8a0e4be6e5968314cb64cf305f96cf6ba873)	Ratio
> `Block 9422905`	`7852` ops/sec (`±3.97%`)	`20083` ops/sec (`±2.68%`)	`2.56`
> `Block 9422906`	`7804` ops/sec (`±4.43%`)	`18947` ops/sec (`±6.66%`)	`2.43`
> `Block 9422907`	`8582` ops/sec (`±2.81%`)	`19661` ops/sec (`±2.42%`)	`2.29`
> `Block 9422908`	`8037` ops/sec (`±7.32%`)	`19394` ops/sec (`±2.56%`)	`2.41`
> This comment was automatically generated by [workflow](https://github.com/ethereumjs/ethereumjs-monorepo/actions?query=workflow%3AVM) using [github-action-benchmark](https://github.com/marketplace/actions/continuous-benchmark).

The type was faster.

2022-08-04 20:04 UTC, acolytec3 approved these changes
LGTM

2022-08-04 20:05 UTC, merged

2022-08-05 11:31 UTC, holgerd77 commented
@g11tech congrats to the merge of this, also just skimmed through the code, looks pretty great! 🎉 Can't wait to test this out at some point, would this be done through the snippet you commented out in the code? What would one see in the console!

Anyhow: great progress! ❤️ 🤩

2022-08-06 16:25 UTC, g11tech commented
> @g11tech congrats to the merge of this, also just skimmed through the code, looks pretty great! tada Can't wait to test this out at some point, would this be done through the snippet you commented out in the code? What would one see in the console!
> 
> Anyhow: great progress! heart star_struck

thanks @holgerd77 yea pretty exciting, the output (for an sample `AccountRange`) should be something like this  which @scorbajio has been able to recreate (with the flag `--forceSnapSync`
https://github.com/ethereumjs/ethereumjs-monorepo/pull/2107#issuecomment-1207145161