Blockchain, VM, Client: New Bugfix Releases
ethereumjs/ethereumjs-monorepo pull request #1932
Opened 2022-06-03 20:00 UTC by holgerd77

@ryanio made me aware that I had forgotten a release for the Blockchain library containing the last-minute fix from #1931.

This PR catches up on this, it also includes new releases for VM and Client so that the changes are surely applied.

PR is targeted towards `v5-maintenance` so that it doesn't interrupt the current (rebase and the like) processes.

2022-06-03 20:08 UTC, ryanio approved these changes
lgtm! thanks!

2022-06-03 20:13 UTC, merged

2022-06-03 20:22 UTC, holgerd77 commented
Just released the following versions on npm:

- `@ethereumjs/blockchain` [5.5.3](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fblockchain%405.5.3)
- `@ethereumjs/vm` [5.9.2](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fvm%405.9.2)
- `@ethereumjs/client` [0.5.1](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fclient%400.5.1)

2022-06-03 20:26 UTC, holgerd77 commented
Tested by starting and re-starting Rinkeby sync on the client. Works! 🙂

2022-06-15 21:48 UTC, Dayday10 requested changes
?