chore: upgrade `eslint` to `^8.0.0`
ethereumjs/ethereumjs-monorepo pull request #2095
Opened 2022-08-03 11:38 UTC by faustbrian

Upgrades `eslint` to the latest major release

2022-08-03 11:40 UTC, holgerd77 commented
The man who does all the work at once. 😂

(but great thing to tackle, maybe I've got too much respect for these kind of work tasks... 😜)

2022-08-03 11:49 UTC, holgerd77 commented on packages/client/.eslintrc.js
> +    extraFileExtensions: ['.json'],
Does this include/activate linting on JSON files?

2022-08-03 12:26 UTC, holgerd77 commented on packages/client/.eslintrc.js
> +    extraFileExtensions: ['.json'],
Ah no, I think linting for JSON is great. 👍 (not sure if there are other opinions here)

2022-08-03 23:14 UTC, acolytec3 requested changes
Looks good.  One deletion of archaic references and this looks ready for merging to me.

2022-08-04 00:18 UTC, acolytec3 commented
> @acolytec3 what should be deleted?

Ugh, sorry, VS Code ate my comments again. The `env: mocha` in the eslint config in `rlp`

2022-08-04 00:27 UTC, acolytec3 approved these changes
LGTM.  @holgerd77 anything else to add?

2022-08-04 09:21 UTC, holgerd77 commented
> @holgerd77 [88c2563](https://github.com/ethereumjs/ethereumjs-monorepo/commit/88c25636d322716a962136885b461b617bea9816)

Also the name in the header title, so `# rlp` -> `# @ethereumjs/rlp`

2022-08-04 09:22 UTC, holgerd77 commented
@faustbrian we are doing our team call today at 5:30pm Berlin time, if you are interested you are very invited to join, then I'll send you a link.

2022-08-04 09:34 UTC, holgerd77 commented on packages/client/lib/rpc/modules/engine.ts
> +        await this.service.beaconSync?.setHead(headBlock)
Oh, linting already at our service (or is this no rule and you side-discovered?) 🙂

2022-08-04 09:38 UTC, holgerd77 commented on packages/client/lib/rpc/modules/engine.ts
> +        await this.service.beaconSync?.setHead(headBlock)
But it wasn't added in this PR or was it (can't find)? (just out of interest, wonder how this was triggered?)

2022-08-04 09:53 UTC, holgerd77 commented on packages/client/lib/rpc/modules/engine.ts
> +        await this.service.beaconSync?.setHead(headBlock)
Ah, then it's likely some bug in their parser on how to find this locations I guess.

2022-08-04 09:55 UTC, holgerd77 approved these changes
LGTM

2022-08-04 09:55 UTC, merged

2022-08-04 09:56 UTC, holgerd77 commented on packages/client/lib/rpc/modules/engine.ts
> +        await this.service.beaconSync?.setHead(headBlock)
Thanks a lot for the upgrade here, just merged! 🙂