Invalid README examples
ethereumjs/ethereumjs-monorepo pull request #2247
Opened 2022-08-29 19:48 UTC by rodrigoherrerai

1. Blockchain cannot be used to initiate an EVM, it is not "EVMOpts". 
2. "gasUsed" is not of type "ExecResult"

2022-08-29 19:58 UTC, acolytec3 requested changes
Thanks for the PR and catching these misses.  Please note the one requested change.  Thanks!

2022-08-29 19:58 UTC, acolytec3 commented on packages/evm/README.md
> -    console.log(`gasUsed : ${results.gasUsed.toString()}`)
Instead of deleting this, let's just print the correct value.

`console.log(`gasUsed: ${result.executionGasUsed.toString()}`)`

2022-08-29 20:22 UTC, acolytec3 approved these changes
LGTM, thanks for the PR!

2022-08-29 20:22 UTC, rodrigoherrerai commented
@acolytec3 
Done !

2022-08-29 20:43 UTC, merged

2022-08-31 08:04 UTC, holgerd77 commented
@acolytec3 short reminder: please post-label external PRs. 🙂

2022-08-31 08:09 UTC, holgerd77 commented on packages/evm/README.md
>  const eei = new EEI(stateManager, common, blockchain)
This has still (minimally) two things in it which breaks the example:

1. the `DefaultStateManager()` doesn't accept a `common` object any more
2. `blockchain` is still passed to EEI but initialization has now been removed by the PR

Sorry guys, but: 1 Submitter, 1 Reviewer, this is a bit too much for a 3 LOC change. 🤨 Can you please *run* an example you want to improve at least once?