client: add proofs to blobsbundle
ethereumjs/ethereumjs-monorepo pull request #2642
Opened 2023-04-14 18:53 UTC by g11tech

Add proofs to blobsbundle and consequently to getblobsbundle engine api call so that CL doesn't need to compute proof which ideally would be coming packaged in the network wrapper serialized tx

ref:
- https://github.com/ethereum/execution-apis/pull/392

2023-04-17 07:11 UTC, holgerd77 commented
Rebased this via UI

2023-04-17 10:19 UTC, holgerd77 requested changes
It would be good to have at least 1-2 small test cases for this so to minimally make sure that data is passed around and encoded/decoded in the correct format.

2023-04-18 05:25 UTC, g11tech commented on packages/client/test/miner/pendingBlock.spec.ts
> +    st.ok(blobProof !== undefined && equalsBytes(blobProof, proofs[0]))
@holgerd77 this checks if the bundle has the proof and valdiates it as well

2023-04-18 05:26 UTC, g11tech commented
rebased via UI again

2023-04-18 09:33 UTC, holgerd77 approved these changes
LGTM

2023-04-18 09:34 UTC, merged