Block, VM: Unify hardforkBy Options
ethereumjs/ethereumjs-monorepo pull request #2800
Opened 2023-06-19 20:28 UTC by holgerd77

Second part of #2774 following #2798

This PR does the following:

- Block: unify `hardforkByBlockNumber`, `hardforkByTTD` options -> `setHardfork`
- VM (constructor/runBlock()): unify `hardforkByBlockNumber`, `hardforkByTTD` options -> `setHardfork`

2023-06-19 21:47 UTC, jochem-brouwer submitted a review, later dismissed
LGTM

2023-06-20 00:39 UTC, acolytec3 commented on packages/block/src/header.ts
> +    if (typeof setHardfork !== 'boolean') {
Could this be simplified to just the below?

```suggestion
    else {
```

2023-06-20 00:45 UTC, acolytec3 commented on packages/block/src/header.ts
> +    if (typeof setHardfork !== 'boolean') {
```suggestion
    else if (typeof setHardfork !== 'boolean') {
```

2023-06-20 00:49 UTC, acolytec3 commented on packages/vm/src/runBlock.ts
> +    if (typeof setHardforkUsed !== 'boolean') {
```suggestion
    else if (typeof setHardforkUsed !== 'boolean') {
```

2023-06-20 00:57 UTC, acolytec3 requested changes
I could be missing the significance but requested one change in how we evaluate the `setHardfork` opt so we don't check it twice (if it's indeed `true`).  Small efficiency gain if I'm not missing something.  Otherwise, looks great!

2023-06-20 07:35 UTC, holgerd77 commented
@jochem-brouwer @acolytec3 thanks for reviewing 🙂, have applied the suggested changes, needs re-approval now! 🙂

2023-06-20 07:39 UTC, jochem-brouwer submitted a review, later dismissed
Ah right, good catch @acolytec3. LGTM still! :smile: (assuming CI passes)

2023-06-20 07:40 UTC, jochem-brouwer commented
Nvm, CI fails. I should not approve so fast :sweat_smile: (how do I dismiss my review?)

2023-06-20 07:45 UTC, jochem-brouwer commented
Will re-approve if CI passes

2023-06-20 07:49 UTC, g11tech approved these changes
looks amazing! :rocket: :heart:

2023-06-20 09:23 UTC, merged