Snap Sync Fetchers: Highest Known Hash Optimization
ethereumjs/ethereumjs-monorepo pull request #2941
Opened 2023-08-06 20:14 UTC by scorbajio

2023-08-07 19:05 UTC, scorbajio commented
Optimizing the storage fetcher is more complicated since the response for `getStorageRanges` is a double array. Will handle that in a future PR.

2023-08-10 05:18 UTC, g11tech requested changes
blocking till 
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2950 

is merged so that the PR can be merged with keyHashing enabled

2023-08-14 08:17 UTC, g11tech commented
will test this out today @scorbajio :+1:

2023-08-14 08:37 UTC, g11tech commented on packages/client/src/sync/fetcher/accountfetcher.ts
> +    if (this.highestKnownHash && compareBytes(limit, this.highestKnownHash) < 0) {
ahh so this solves the problem that if some range is empty it won't be requested :+1:

2023-08-14 08:38 UTC, g11tech commented
from the code review it seems that we would need similar optimization in storage fetcher?

2023-08-14 18:01 UTC, scorbajio commented
> from the code review it seems that we would need similar optimization in storage fetcher?

Yes, but since the optimization for the storage fetcher is more complicated, I'm planning on doing it in a followup PR.

2023-08-15 07:32 UTC, g11tech approved these changes

2023-08-15 07:57 UTC, merged