handle an edge case in newpayload block execution
ethereumjs/ethereumjs-monorepo pull request #3131
Opened 2023-10-31 12:32 UTC by g11tech

handle an edgecase noticed during holesky sync

2023-10-31 13:45 UTC, acolytec3 requested changes

2023-10-31 13:45 UTC, acolytec3 commented on packages/client/src/rpc/modules/engine.ts
> +          // at Blockchain.getBlock (/home/gajinder/ethereumjs-monorepo/packages/blockchain/src/blockchain.ts:763:15)
Do we need this entire stack trace in the logs?

2023-10-31 13:46 UTC, acolytec3 reviewed
Generally looks good.  Do we need a specific test for this edge case or is this covered by existing tests?

2023-11-01 09:27 UTC, holgerd77 approved these changes
I would really really like to get things prepared for a release round tomorrow, at least if things work on a somewhat descent level (just re-running Holesky again right now).

I would therefore merge here, maybe we can add an eventual test later on.

Thanks! 🙏

2023-11-01 09:27 UTC, merged