Block: treeshaking tasks
ethereumjs/ethereumjs-monorepo pull request #3586
Opened 2024-08-13 23:03 UTC by ScottyPoi

2024-08-14 01:17 UTC, acolytec3 submitted a review, later dismissed
I generally really like this approach.  One nit about `normalizeTxParams` that we should address (though can be in a different PR if you want).

2024-08-14 01:17 UTC, acolytec3 commented on packages/block/src/block/constructors.ts
> +export function normalizeTxParams(_txParams: any) {
Two things on this function:
1) It isn't a constructor so ideally we put it in a helpers/utils file.  
2) We have essentially the same function [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/659d4280609943effe5322dcec7747a0cb6e50f8/packages/tx/src/fromRpc.ts#L5).  Can we harmonize these two and consolidate in one location (maybe in `@ethereumjs/util/helpers.ts` or `internal.ts`)  The only real difference I see is converting `0x0` to `0x` in the transaction signatuere values.

2024-08-14 08:13 UTC, holgerd77 approved these changes
LGTM

2024-08-14 08:13 UTC, merged

2024-08-25 10:42 UTC, Jamiecaty requested changes

2024-08-25 10:42 UTC, Jamiecaty commented on packages/block/src/block/constructors.ts
>    ConsolidationRequest,
- [ ]

2024-08-25 10:44 UTC, Jamiecaty approved these changes