Add tests for partial account helper functions
ethereumjs/ethereumjs-monorepo pull request #3745
Opened 2024-10-17 01:10 UTC by scorbajio

This change adds unit tests testing a variety of cases for the partial account helper functions:
* `createPartialAccount`
* `createPartialAccountFromRLP`
* `serializeWithPartialInfo`

2024-10-17 07:44 UTC, holgerd77 reviewed
Is this AI generated? If so can we please establish the convention (within the whole team) to always clearly mark/label this as such?

If so, we should clearly exchange on some best practices on how to review such code and what expectation we put on it.

If not: my apologies. 😂

2025-02-05 14:59 UTC, jochem-brouwer reviewed
The tests themselves look good! However, if you create a partial account from some data and then assert later it is the correct account (with the same, copied data) it is more clean to read these variables from data and then compare those (now the values are copied, so if you change one value you also have to change it on another place. If it's in a const var, only one place needs to be edited)

2025-02-05 14:59 UTC, jochem-brouwer commented on packages/util/test/account.spec.ts
> +    assert.deepEqual(account, new Account(1n, Units.ether(1), KECCAK256_RLP, KECCAK256_RLP, 10, 1))
For this test, could you arrange the used data in a `const` variable and read from there? (This makes the test more robust and clear)

2025-02-05 14:59 UTC, jochem-brouwer commented on packages/util/test/account.spec.ts
> +    )
The same for this test, use a `const` data variable to read from.

2025-02-05 15:03 UTC, gabrocheleau requested changes
Left some comments

2025-02-07 20:38 UTC, scorbajio commented on packages/util/test/account.spec.ts
> +    assert.deepEqual(account, new Account(1n, Units.ether(1), KECCAK256_RLP, KECCAK256_RLP, 10, 1))
Fixed this.

2025-02-07 20:40 UTC, scorbajio commented on packages/util/test/account.spec.ts
> +    )
Fixed

2025-02-07 20:42 UTC, scorbajio commented on packages/util/test/account.spec.ts
> +    assert.deepEqual(account, new Account(1n, Units.ether(1), KECCAK256_RLP, KECCAK256_RLP, 10, 1))
I've pulled out the field data into a const variable and am using that to both create the account and check for equality.

2025-02-07 20:46 UTC, scorbajio commented on packages/util/test/account.spec.ts
> +  })
I've switched over to keeping the tests in an array that gets run as a part of a loop. It's not less lines of code, but it is more readable since the data being serialized is very similar. If I had disposed of the test description strings, it would have been much DRYer, but I think the descriptions are useful, so I kept them.

2025-02-07 22:07 UTC, jochem-brouwer approved these changes
LGTM!

2025-02-08 02:30 UTC, gabrocheleau approved these changes
Thanks for addressing all the comments! lgtm

2025-02-08 02:30 UTC, merged